# Generated by Django 3.2.5 on 2021-08-01 01:07

from django.db import migrations, models
import property.constants


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('status', models.CharField(choices=[(property.constants.PropertyStatus['PRE_SOLD'], 'PRE_SOLD'), (
                    property.constants.PropertyStatus['AVAILABLE'], 'AVAILABLE'), (
                                                         property.constants.PropertyStatus['SOLD'], 'SOLD')], max_length=30)),
                ('address', models.CharField(max_length=40)),
                ('city', models.CharField(max_length=30)),
                ('state', models.CharField(max_length=30)),
                ('price', models.CharField(max_length=30)),
                ('description', models.TextField(blank=True)),
                ('year', models.CharField(max_length=30)),
            ],
        ),
    ]
