# Generated by Django 3.2.5 on 2021-08-01 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0004_propertycustomer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='propertycustomer',
            old_name='customer',
            new_name='user',
        ),
    ]
